name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o jiq-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o jiq-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o jiq-windows-amd64.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jiq-linux-amd64
            jiq-darwin-amd64
            jiq-windows-amd64.exe